const AdministrarPacientes = () => {
    return (
        <>
                <h1>Desde Administrar Paciente</h1>
                <div class="relative z-10 bg-white rounded-xl shadow-xl ring-1 ring-slate-900/5 dark:bg-slate-800 dark:highlight-white/10"><article><h2 class="text-lg font-semibold text-slate-900 pt-4 pb-2 px-4 sm:px-6 lg:px-4 xl:px-6 dark:text-slate-100 transition-opacity duration-[1.5s] delay-500 opacity-25">Weekly one-on-one</h2><dl class="flex flex-wrap divide-y divide-slate-200 border-b border-slate-200 text-sm sm:text-base lg:text-sm xl:text-base dark:divide-slate-200/5 dark:border-slate-200/5"><div class="px-4 sm:px-6 lg:px-4 xl:px-6 pb-4"><dt class="sr-only">Date and time</dt><dd class="transition-opacity duration-[1.5s] delay-500 opacity-25"><time datetime="2020-11-15T10:00:00-05:00">Thu Nov 15, 2020 10:00am</time> - <time datetime="2020-11-15T11:00:00-05:00">11:00am<span class="sr-only sm:not-sr-only"> EST</span></time></dd></div><div class="w-full flex-none flex items-center p-4 sm:p-6 lg:p-4 xl:p-6"><dt class="w-2/5 sm:w-1/4 flex-none text-slate-900 font-medium dark:text-slate-300 transition-opacity duration-[1.5s] delay-500 opacity-25">Location</dt><dd class="transition-opacity duration-[1.5s] delay-500 opacity-25">Kitchener, <abbr title="Ontario">ON</abbr></dd></div><div class="w-full flex-none flex items-center p-4 sm:p-6 lg:p-4 xl:p-6"><dt class="w-2/5 sm:w-1/4 flex-none text-slate-900 font-medium dark:text-slate-300 transition-opacity duration-[1.5s] delay-500 opacity-25">Description</dt><dd class="italic transition-opacity duration-[1.5s] delay-500 opacity-25">No meeting description</dd></div><div class="w-full flex-none flex items-center p-4 sm:py-5 sm:px-6 lg:p-4 xl:py-5 xl:px-6"><dt class="w-2/5 sm:w-1/4 flex-none text-slate-900 font-medium dark:text-slate-300 transition-opacity duration-[1.5s] delay-500 opacity-25">Attendees</dt><dd class="text-sm font-medium text-slate-700 bg-slate-100 rounded-full py-1 px-3 dark:bg-slate-700 dark:text-slate-300 transition-opacity duration-[1.5s] delay-500 opacity-25">Andrew McDonald</dd></div></dl><div class="grid grid-cols-2 gap-x-4 sm:gap-x-6 lg:gap-x-4 xl:gap-x-6 p-4 sm:px-6 sm:py-5 lg:p-4 xl:px-6 xl:py-5"><div class="text-base font-medium rounded-lg bg-slate-100 text-slate-900 py-3 text-center cursor-pointer dark:bg-slate-600 dark:text-slate-400 dark:highlight-white/10">Decline</div><div class="text-base font-medium rounded-lg bg-sky-500 text-white py-3 text-center cursor-pointer dark:highlight-white/20">Accept</div></div></article></div>
        </>

    )
}
export default AdministrarPacientes;